### ISSUE TITLE
Lag/unresponsive page issue

### ISSUE THREAD

**Issue by mighty-phoenix** [Sur-un-nuage/strapi-plugin-expo-notifications#4]
The plugin page "My Notifications" becomes unresponsive and very laggy. This didn't happen before, but as my user base grew to 1 million, the issue arises.
Can you quickly guide me regarding how I may fix this behaviour? I simply want to send notifications to all my users.
Thanks!
Quick help would be highly appreciated. @philohelp @isaacsolutionstech

**Comment by philohelp** [comment]
Thanks, I'll check that

**Comment by mighty-phoenix** [comment]
Thanks! @philohelp 
Will be very obliged if you could let me know how I can fix this issue.
Facing issues in sending the notifications in production due to this.
Even if I wait for the page to be responsive again until the "Receivers" section gets populated, the page gets absolutely stuck when I click on "Select all"
After waiting on clicking "Select all", the tab crashes showing "Aw snap!", before it does, I can see that the tab uses too much RAM(memory) I think.
The issue clearly seems to be the large amount of rendered data
Thanks again!

**Comment by philohelp** [comment]
Ok, here are my initial thoughts on this:

1- Eliminating User Visualization:
You don't need to visualize a huge list of users, so it would be better to remove this part. This can be easily achieved with a flag added to the configuration file: "Don't show the receivers". If true, there will be no more user list to manage, the editor will simply have to write the message and hit send. The sending process itself will then occur on the server.

2- Challenges in Sending Notifications:
- It's not feasible to retrieve so many users at once (a limitation of Strapi).
- Even if it were possible, you couldn't send more than a certain number of notifications at once. I don't have the exact limit for the Expo API, but I wouldn't be surprised if it only allowed 1000 messages per batch.

3- Repetitive Process:
You could try to implement a recursive process that fetches 1000 users, then prepares and attempts to send 1000 messages via Expo, repeating the operation 1000 times.

4- Managing Success/Failure Information:
In theory, I believe that this could work, but then you would have to deal with a massive amount of information related to the success or failure of the notifications. To handle this, you could start by considering that whenever Expo.sendPushNotificationsAsync doesn't return an error, it means that the rest of the process is the sole responsibility of Expo, Apple, and Google. They will retry a certain number of times, and you will have no means to interfere. However, you'll definitely need to manage what happens before - API errors, network errors, etc., and what happens after: delivery errors (e.g., if a user has revoked authorization) coming back in the form of tickets.

5- Handling Failures and Retrying Attempts:
Then, you would need to retrieve only the failed messages that deserve another chance and store them in a fast database (I like Redis for this) in order to repeat the process a certain number of times.

**Comment by philohelp** [comment]
Ok, here are my initial thoughts on this:

1- Eliminate user visualization

You don't need to visualize a huge list of users, so it would be better to remove this part. This can be easily achieved with a flag added to the configuration file: "Don't show the receivers". If true, there will be no more user list to manage, the editor will simply have to write the message and hit send. The sending process itself will then occur on the server.

2- Send the notifications

It's not feasible to retrieve so many users at once (a limitation of Strapi). Even if it were possible, you couldn't send more than a certain number of notifications at once. I don't have the exact limit for the Expo API, but I wouldn't be surprised if it only allowed 1000 messages per batch.

You could try to implement a recursive process that fetches 1000 users, then prepares and attempts to send 1000 messages via Expo, repeating the operation 1000 times.

In theory, I believe that this could work, but then you would have to deal with a massive amount of information related to the success or failure of the notifications. 

3- Handle failures and retry attempts

To handle this, you could start by considering that whenever Expo.sendPushNotificationsAsync doesn't return an error, it means that the rest of the process is the sole responsibility of Expo, Apple, and Google. They will retry a certain number of times, and you will have no means to interfere. 

However, you'll definitely need to manage what happens before - API errors, network errors, etc., and what happens after: delivery errors (e.g., if a user has revoked authorization) coming back in the form of tickets.

To achieve this, you would need to retrieve only the failed messages that deserve another chance and store them in a fast database (I like Redis for this) in order to repeat the process a certain number of times.
